### ISSUE TITLE
@import timepicker

### ISSUE THREAD

**Issue by bobking256** [Wikiki/bulma-extensions#105]
I am trying to use latest version of bulimia-calendar but when I try to build I get @import timepicker issue.  "Can't find stylesheet to import".  Is there a way to resolve?

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import timepicker
       ^
      Can't find stylesheet to import.
   ╷
19 │ @import timepicker

**Comment by Navrug42** [comment]
Hi,

Can you please give more details about the build command you're using and the steps you've followed ?

**Comment by bobking256** [comment]
$ npm run dev

**Comment by bobking256** [comment]
working on a mac.  $npm run dev

**Comment by bobking256** [comment]
Here is a complete dump:

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import timepicker
       ^
      Can't find stylesheet to import.
   ╷
19 │ @import timepicker
   │         ^^^^^^^^^^
   ╵
  node_modules/bulma-extensions/bulma-calendar/dist/css/bulma-calendar.sass 19:9  @import
  resources/sass/bulma-extensions.sass 7:9                                        @import
  resources/sass/bulma.sass 18:9                                                  @import
  stdin 6:9                                                                       root stylesheet
      in /Users/bobking/Sites/laravel/mms/node_modules/bulma-extensions/bulma-calendar/dist/css/bulma-calendar.sass (line 19, column 9)
    at runLoaders (/Users/bobking/Sites/laravel/mms/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/bobking/Sites/laravel/mms/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/bobking/Sites/laravel/mms/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/bobking/Sites/laravel/mms/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at render (/Users/bobking/Sites/laravel/mms/node_modules/sass-loader/lib/loader.js:52:13)
    at Function.$2 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:24106:48)
    at w6.$2 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:15161:15)
    at u6.v7 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9031:42)
    at u6.v6 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9033:32)
    at ik.uh (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8373:46)
    at tF.$0 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8515:7)
    at Object.ex (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1532:80)
    at aj.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8436:3)
    at iz.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8366:25)
    at iz.cA (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8353:6)
    at p8.cA (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8143:35)
    at Object.n (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1405:19)
    at /Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:5110:51
    at ww.a (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1416:71)
    at ww.$2 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8158:23)
    at v9.$2 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8153:25)
    at u6.v7 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9031:42)
    at u6.v6 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9033:32)
    at ik.uh (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8373:46)
    at tF.$0 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8515:7)
    at Object.ex (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1532:80)
    at aj.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8436:3)
    at iz.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8366:25)
    at iz.cA (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8353:6)
    at Object.eval (eval at BU (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:656:15), <anonymous>:3:37)
    at u6.v7 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9031:42)
    at u6.v6 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9033:32)
    at ik.uh (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8373:46)
    at tF.$0 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8515:7)
    at Object.ex (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1532:80)
    at aj.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8436:3)
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import timepicker
       ^
      Can't find stylesheet to import.
   ╷
19 │ @import timepicker
   │         ^^^^^^^^^^
   ╵
  node_modules/bulma-extensions/bulma-calendar/dist/css/bulma-calendar.sass 19:9  @import
  resources/sass/bulma-extensions.sass 7:9                                        @import
  resources/sass/bulma.sass 18:9                                                  @import
  stdin 6:9                                                                       root stylesheet
      in /Users/bobking/Sites/laravel/mms/node_modules/bulma-extensions/bulma-calendar/dist/css/bulma-calendar.sass (line 19, column 9)
 @ ./resources/sass/app.scss 2:14-254
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bobking/.npm/_logs/2019-03-15T12_18_14_674Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by bobking256** [comment]
FYI, I get the same error if I import only the calendar (via $ npm install bulma-calendar)

**Comment by Wikiki** [comment]
Hi,

Thanks for logs. I'll have a look into it.

**Comment by Wikiki** [comment]
Hi,

I suppose its because the import use the file in <code>dist/css/bulma-calendar.sass</code> so, timepicker is not available at this place.
Can you please uwith the version in "master" branch it should have been fixed. (I'll update npm version soon)

**Comment by bobking256** [comment]
Sorry for delay, I was distracted with another project.  I copied and pasted master branch.  Perhaps this is not the right approach as I am now getting other errors:

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

	&.is-#{$name}
^
      Top-level selectors may not contain the parent selector "&".
    ╷
122 │     &.is-#{$name}
    │     ^^^^^^^^^^^^^
    ╵
  node_modules/bulma-extensions/bulma-calendar/dist/css/timepicker.sass 122:2     @import
  node_modules/bulma-extensions/bulma-calendar/dist/css/bulma-calendar.sass 19:9  @import
  resources/sass/bulma-extensions.sass 7:9                                        @import
  resources/sass/bulma.sass 18:9                                                  @import
  stdin 6:9                                                                       root stylesheet
      in /Users/bobking/Sites/laravel/mms/node_modules/bulma-extensions/bulma-calendar/dist/css/timepicker.sass (line 122, column 2)
    at runLoaders (/Users/bobking/Sites/laravel/mms/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/bobking/Sites/laravel/mms/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/bobking/Sites/laravel/mms/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/bobking/Sites/laravel/mms/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at render (/Users/bobking/Sites/laravel/mms/node_modules/sass-loader/lib/loader.js:52:13)
    at Function.$2 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:24106:48)
    at w6.$2 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:15161:15)
    at u6.v7 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9031:42)
    at u6.v6 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9033:32)
    at ik.uh (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8373:46)
    at tF.$0 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8515:7)
    at Object.ex (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1532:80)
    at aj.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8436:3)
    at iz.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8366:25)
    at iz.cA (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8353:6)
    at p8.cA (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8143:35)
    at Object.n (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1405:19)
    at /Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:5110:51
    at ww.a (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1416:71)
    at ww.$2 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8158:23)
    at v9.$2 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8153:25)
    at u6.v7 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9031:42)
    at u6.v6 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9033:32)
    at ik.uh (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8373:46)
    at tF.$0 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8515:7)
    at Object.ex (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1532:80)
    at aj.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8436:3)
    at iz.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8366:25)
    at iz.cA (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8353:6)
    at Object.eval (eval at BU (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:656:15), <anonymous>:3:37)
    at u6.v7 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9031:42)
    at u6.v6 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:9033:32)
    at ik.uh (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8373:46)
    at tF.$0 (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8515:7)
    at Object.ex (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:1532:80)
    at aj.bb (/Users/bobking/Sites/laravel/mms/node_modules/sass/sass.dart.js:8436:3)
 @ ./resources/sass/app.scss

**Comment by Wikiki** [comment]
Fixed. See https://github.com/Wikiki/bulma-calendar/commit/e47731e689f69480fbc1726a57acb213f67dd399
